### ISSUE TITLE
ModuleNotFoundError: No module named 'molvoxel.voxelizer'

### ISSUE THREAD

**Issue by ybw202056** [SeonghwanSeo/molvoxel#1]
after
`pip install molvoxel`
when I get started, I find an import error.
```
>>> import molvoxel
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\ProgramFiles\Anaconda3\envs\ybw\Lib\site-packages\molvoxel\__init__.py", line 1, in <module>
    from .voxelizer import *
ModuleNotFoundError: No module named 'molvoxel.voxelizer'

```
This error is caused by pip install.

If I download the source code, and use `python setup.py install` to install, the problem get fixed.

Please check the pip install problem

**Comment by SeonghwanSeo** [comment]
Thanks for letting me know.
I released 0.1.3 right now with bug fix.
Sorry for inconvenience.
